### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by FredericBr** [schorschinho/osprey#128]
Dear Georg and al.,

I used your software all the day. It works like charm.
Thanks for this valuable work.

I just have some suggestion to improve it:
1. In the CSV result, it could be great to add the name of the subject as another variable.
2. In addition to the 'Raincloud plot tools', it could be great to have all the spectrum and the results generate in pdf; easier way to visualize the data (like in Tarquin or LCModel).
3. Where is it possible to find the quality-control data from each spectra (in .csv, or other format)?

If I can help you, let me know.
Thanks once again,

Frederic

**Comment by hezoe100** [comment]
Dear Frederic,

Thank you for your positive feedback and your suggestions. It's much appreciated.

Just two quick comments on your inquiry: 
1. This depends whether you define subject name as de-identified file or folder name of the acquisition or as the subject name stored in the raw data. We would want to avoid storing the latter. The de-identified file name could possibly be fed back into the CSV stat file, as we would want to keep the CSV results as numbers only.

2. In the current implementation pdfs can be generated manually for all module steps, but only within the GUI. We implemented it this way as we wanted to avoid generating a large number of pdfs which are redundant to the GUI. However, we could make this a user's choice by adding this into the jobFile.

If you have any other suggestions or questions, please let me know.
Thanks for your feedback,

Helge

**Comment by FredericBr** [comment]
Dear Helge,

Thanks for your quick reply.
1. Indeed, I spoke about the de-identified file name, thanks to the folder name (here in BIDS; i.e. 'sub-1').
2. A pdf option like a user's choice by adding it into the jobFile, could be great!
3. In these latter (csv output and pdf), add the quality-control data could be a real asset for your software. A sort of safeguard against the misuse of the results.

Best, and thanks again for this software,

Frederic

**Comment by FredericBr** [comment]
Great work @hezoe100 
I will try it in a couple of days!
