### ISSUE TITLE
bug: saveJMRUI and savejMRUI

### ISSUE THREAD

**Issue by P-VS** [schorschinho/osprey#176]
Dear,

I an attempt to compare the Osprey fitting results with those from jMRUI for my data, I found a bug in your code.

In the job .m example files and in the ‘OspreyJob.m’ file, you use the opts.saveJMRUI tag. However in, the MRSCont.mat data structure and in the ‘OspreyGUI.m’ files, you use the opts.savejMRUI tag. Since savejMRUI and saveJMRUI are different parameters in Matlab, Osprey never writes the requested jMRUI files. If I change it in the job .m example files and the ‘OspreyJob.m’ file to savejMRUI, it works fine.

Kind regards,
Dr. Peter Van Schuerbeek

**Comment by hezoe100** [comment]
Dear Dr. Van Schuerbeek,

Thank you for using Osprey and reporting back those issues to us. Osprey is still under development and any user feedback is appreciated. 

I've now fixed the jMRUI export problem. Let me know if you experience any other problems or if you want to give us feedback/suggestions.

Best,
Helge Zöllner
