### ISSUE TITLE
[BUG] Error during PDF creation outside GUI

### ISSUE THREAD

**Issue by nwd2918** [schorschinho/osprey#242]
**Describe the bug**
When running an analysis using individual commands rather than the GUI an error occurs during the creation of figure PDFs. For example, when running `OspreyLoad`:

```
Reference to non-existent field 'Load'.

Error in osp_plotModule (line 87)
            Title = [MRSCont.ver.Osp ' ' MRSCont.ver.Load];

Error in osp_plotAllPDF (line 37)
                osp_plotModule(MRSCont, 'OspreyLoad', kk, 'mets');

Error in OspreyLoad (line 141)
    osp_plotAllPDF(MRSCont, 'OspreyLoad')

Error in osp_onLoad (line 32)
    MRSCont = OspreyLoad(MRSCont);
 
Error while evaluating UIControl Callback.
```

This happens with all commands, not just `OspreyLoad`.

The issue is resolved by changing the relevant line in `osp_plotModule.m` from

`Title = [MRSCont.ver.Osp ' ' MRSCont.ver.Load];`

to 

`Title = [MRSCont.ver.Osp ' Load'];`

Equivalent changes in the relevant lines for `OspreyProcess`, `OspreyFit`, etc, resolve the issue for them also. However, I'm not sure if this change removes some intended functionality. 

**Computer configuration:**
 - OS: Ubuntu 18.04
 - MATLAB version 2020b

**Comment by HJZollner** [comment]
Hi!

Thanks for reporting this bug. We did actually remove the individual version tags of the module in release v1.0.0, but this plot function has slipped the testing. 

We have fixed this issue in #243 

Helge
