### ISSUE TITLE
[BUG] Gunzipped file problem in osp_plotCoreg

### ISSUE THREAD

**Issue by nwd2918** [schorschinho/osprey#246]
**Describe the bug**
When generating PDFs from the `OspreyCoreg` command, the following error occurs:

```
Error using spm_slice_vol
Cant open image file.

Error in voxel2world_space (line 32)
img_t = spm_slice_vol(V,TM,TD,2)';

Error in osp_plotCoreg (line 76)
[mask_t,mask_c,mask_s] = voxel2world_space(Vmask,voxel_ctr);

Error in osp_plotModule (line 464)
                osp_plotCoreg(MRSCont, kk);

Error in osp_plotAllPDF (line 91)
              osp_plotModule(MRSCont, 'OspreyCoreg', kk);

Error in OspreyCoreg (line 193)
    osp_plotAllPDF(MRSCont, 'OspreyCoreg')
```

The ultimate issue appears to be in `osp_plotCoreg`. Here, the voxel mask must be converted from a .nii.gz file to .nii in order to be read by `spm_slice_vol`. This is done successfully at lines 59 and 60:

```
Vmask=spm_vol(MRSCont.coreg.vol_mask{kk}{VoxelIndex}.fname);    
voxel_ctr = MRSCont.coreg.voxel_ctr{kk}(:,:,VoxelIndex); 
```

The following lines (63-70)

```
if ~MRSCont.flags.didSeg
     if exist([MRSCont.coreg.vol_mask{kk}.fname, '.gz'],'file')
         delete(MRSCont.coreg.vol_mask{kk}.fname);
     end
     if exist([MRSCont.coreg.vol_image{kk}.fname, '.gz'],'file')
         delete(MRSCont.coreg.vol_image{kk}.fname);
     end
end
```
 then seem to delete the newly created .nii files before the plotting steps are run. Since the .nii file is missing, there is nothing for `spm_slice_vol` to read and the error results.

Moving this block of code to the end of `osp_plotCoreg` solves this issue and seems to retain the desired functionality (i.e., the .nii file is deleted to leave just the .nii.gz mask file. 

**Computer configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - MATLAB version: 2020b

**Comment by HJZollner** [comment]
Hi! 
Thanks for reporting this issue back to us!

Actually, we did already fix this problem in #245. I did test and fix the osp_plotAllPDF for all modules after you did report the issues with the fit module #244.

Thank you!
Helge
