### ISSUE TITLE
[BUG] Large number of TWIX datasets causes memory issue

### ISSUE THREAD

**Issue by schorschinho** [schorschinho/osprey#28]
A large number of TWIX datasets can cause the memory to overflow and produce an "out of memory" error.

This is because osp_LoadTwix gets all the raw (individual coil) data from all datasets first, and then osp_combineCoils combines them one after another.

Resolution: We have to shift the coil-combination procedure (including the deletion of the individual coil elements from memory) one 'hierarchy level' further down, ie into the osp_LoadTwix function, to free up memory after loading and coil-combining each dataset.

**Comment by hezoe100** [comment]
See Siemens coil combination pull request.

**Comment by schorschinho** [comment]
Fixed through https://github.com/schorschinho/osprey/commit/99a3b3874395486a4f17d9cb98be7f5c2364324f. Thank you, Helge.
