### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alexedmon1** [schorschinho/osprey#342]
**Describe the bug**
Receive a "File does not exist" error while trying to load multiple RDAs into one jobfile using the GUI.

**To Reproduce**
1. Select more than one RDA file for loading into the jobfile
2. Complete the jobfile as normal and execute it. 

**Expected behavior**
Jobfile should execute as normal.

**Screenshots**
>> Osprey
Timestamp October 13, 2021 13:40:33 Osprey 1.1.0  OspreyGUI
Item generic: No field(s) named
frames
Item generic: No field(s) named
frames
Item generic: No field(s) named
frames
Fitting style was changed to Separate, because this is unedited data. Please indicate otherwise in the csv-file or the GUI 
/Users/edm9fd/Documents/CARES/mrs/front/Osprey_FRONT_131021.m
Timestamp October 13, 2021 13:41:19 Osprey 1.1.0
Timestamp October 13, 2021 13:41:19 Osprey 1.1.0  OspreyGUI
Error using osp_detDataType (line 90)
Error during loading. File or folder /Users/edm9fd/Documents/CARES/mrs/front/rda/006-M_front.rda  does not exist. Check
the job file!

Error in OspreyGUI (line 414)
                [~, ~] = osp_detDataType(MRSCont);

Error in CreateOspreyJob_app/CREATEJOBButtonPushed (line 509)
            OspreyGUI(MRSCont);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating DestroyedObject PrivateButtonPushedFcn.

**Computer configuration (please complete the following information):**
 - OS: Mac OS 11.6 Big Sur
 - Version - Latest pull from Git: Today
 - MATLAB version [e.g. 2018a]: 2020b

**Additional context**
When I create a jobfile for each file separately, the GUI is able to read in the files correctly. In the error message, there appears to be an extra space in the filename when setting up for a batch process.

**Comment by HJZollner** [comment]
Hi David,

Thank you for reporting the issue. Two more questions to clarify:

1.  Do you create the jobFile from within the GUI (using the create jobFile button)?
2. Is the GUI working if you create a two rda files jobFile manually and open it with the GUI?

I'll look into the issue within the next days. I need to find some rda files to do so. I guess, it would be quicker if you could send me two of your rda files if you don't mind.

Best,
Helge
