### ISSUE TITLE
[FEATURE REQUEST] HTML Style Report of Outputs

### ISSUE THREAD

**Issue by tjhendrickson** [schorschinho/osprey#356]
**Is your feature request related to a problem? Please describe.**
Depending on system it can sometime be difficult to open PDF files

**Describe the solution you'd like**
Almost all systems can leverage HTML files and HTML files can be easily ingested into neuroimaging data management software (such as LORIS)

**Additional context**
Embedding images within the HTML report would make distribution to collaborators very seamless.

**Comment by HJZollner** [comment]
I have just committed a generalized version of the HTML report that should work for all sequences and especially for the ones used in HBCD.

@CWDAVIESJENKINS Can you double-check whether the outputs are BIDS-compliant and submit any changes if needed? Otherwise we can close this issue.

**Comment by HJZollner** [comment]
Added in the latest version.
