### ISSUE TITLE
[FEATURE REQUEST] BIDS Style Derivative Outputs

### ISSUE THREAD

**Issue by tjhendrickson** [schorschinho/osprey#357]
**Is your feature request related to a problem? Please describe.**
Even though there is no accepted BIDS derivative format for MRS, many of the files outputted actually can be changed to meet the BIDS derivative format. 

**Describe the solution you'd like**
Perhaps having a flag which will output all of the pipeline derivatives in a [BIDS derivative format](https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html). 
Specifically:
- The tabulated data produced per session could emulate the BIDS style suggested for [phenotypic and assessment data](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#phenotypic-and-assessment-data)
- The NIFTI or imaging data like the masks or anatomical images could be renamed slightly.

**Comment by HJZollner** [comment]
We'll have to restructure the tissue maps provided by SPM12 to match BIDS style. This is mainly about moving the results into a different folder, renaming it, and making sure that Osprey finds them.

**Comment by HJZollner** [comment]
Solved in #491
