### ISSUE TITLE
[FEATURE REQUEST] Containerization of Pipeline

### ISSUE THREAD

**Issue by tjhendrickson** [schorschinho/osprey#358]
**Is your feature request related to a problem? Please describe.**
Not all systems come with MATLAB licenses and at times can be difficult to obtain. To lower the barrier of entry and make osprey capable of running on systems without MATLAB, containerization is suggested.

**Describe the solution you'd like**
I would like the application, along with its dependencies wrapped into a container for ease of use. Specifically, MATLAB Compiler Runtime will likely need to be deployed for the containerized application to run as expected.

**Comment by HJZollner** [comment]
Osprey can be compiled as a standalone version now. The server version has been tested in MN and locally. Will need further testing to finalize this as a feature for general use.
