### ISSUE TITLE
[FEATURE REQUEST] Add option to provide external segmentation maps

### ISSUE THREAD

**Issue by schorschinho** [schorschinho/osprey#396]
**Is your feature request related to a problem? Please describe.**
Osprey currently calls SPM to perform segmentation of structural anatomical images, but there is no way to provide pre-segmented tissue class maps instead (e.g. produced by deep-learning methods specifically designed for certain cohorts).

**Describe the solution you'd like**
Add fields to the job file that provide a pathway for supplying pre-segmented tissue class maps.

**Comment by HJZollner** [comment]
External segmentation is supported for different formats these include:

- external probability maps for tissue types (separate 3D volumes or single 4D volume)
- external label maps with binarized results (theses have to be changed manually according to the atlas/lableing convention)
