### ISSUE TITLE
Import Siemens XA (31) data

### ISSUE THREAD

**Issue by karl-koschutnig** [schorschinho/osprey#446]
**Is your feature request related to a problem? Please describe.**
Spectro data from the new Siemens environemnt (in our case XA 31)  can't be loaded.

I am new to Spectroscopy so maybe I am missing some basic things ?!
However, when trying to load a spectrum (*.dat) from our new Siemens Vida (using XA 31), this error message is prompted (see below).

I was able to load the data with another software package (fsl mrs, spec2nii) - just for your info. 

I would really appreciate your help and can of course provide the data if necessary. 
Best, Karl

Loading raw data from dataset   1 out of   1 total datasets...
Software version: VD (!?)
Reader version: 1496740353 (UTC: 06-Jun-2017 09:12:33)
Scan 1/2, read all mdhs:
    97.7 MB read in    2 s
Scan 2/2, read all mdhs:
    93.9 MB read in    1 s

ans =

     0

multi RAID file detected.
Reference to non-existent field 'Frequency'.

Error in io_loadspec_twix (line 474)
    txfrq=twix_obj.hdr.Meas.Frequency;

Error in osp_LoadTwix (line 66)
            raw                         = io_loadspec_twix(MRSCont.files{metab_ll,kk});

Error in OspreyLoad (line 181)
                [MRSCont] = osp_LoadTwix(MRSCont);

Error in osp_onLoad (line 34)
    MRSCont = OspreyLoad(MRSCont);
 
Error while evaluating UIControl Callback.

**Comment by HJZollner** [comment]
Hi Karl,

Thanks for reaching out.Could you share the data with me? (hzoelln2@jhmi.edu)

And you have mentioned that you were able to use spec2nii to convert the data. Have you tried loading the converted spectra with Osprey as it supports .nii MRS format?

Best,
Helge

**Comment by karl-koschutnig** [comment]
Hi Helge, 
I just wanted to check if you had the chance to look at the XA-data? 
If you need another dataset or info - just let me know. 
Best, Karl

**Comment by HJZollner** [comment]
Hi Karl,

Sorry for the delay. Could you re-upload the data for me? I think I've accidentally deleted it from my machine and the download link isn't valid anymore. My apologies for that.

Best,
Helge

**Comment by HJZollner** [comment]
Hi Karl,

I've just added a new feature to the develop branch to support XA31 data. I've tested it with your dataset and the loader works fine.

About the spectra, you send me: You have scanned in the Hippocampus which is an interesting but also very challenging region to target. You'll have to optimize your sequence to achieve sufficient data quality. It looks like you are using the vendor-supplied sequence which is not really optimized - also visible in your data quality. Uzay's post in this thread (https://forum.mrshub.org/t/single-shot-excellency-is-key-for-fmrs/453/5) gives you a good idea of how much can be achieved in terms of data quality with a well-optimized sequence.

If you do have access to other spectroscopy sequences, e.g.: https://www.cmrr.umn.edu/spectro/, it may be worth a shot to use an sLASER localized sequence in this challenging region and spend 1-2 subjects on optimizing the water suppression and gradient directions

Best,
Helge

**Comment by karl-koschutnig** [comment]
Hi Helge,
thank you so much for helping me out!! Really appreciate your effort!

At the moment CMRR is not offering any sequence for XA-Systems. We wanted to go with those sequences in the first place - hope there will be an upgrade available soon?!
Best, Karl
