### ISSUE TITLE
Plotting the fitting results

### ISSUE THREAD

**Issue by Maari13** [schorschinho/osprey#454]
Hi!

Up to recently I used Osprey v1.1.0, but decided to switch to the most recent version now. However, the plotting functions do not work with the same arguments any more as they did in the version I used previously. I used to use them as follows to visualise the metabolite data:
osp_plotLoad(data_container, num_of_dataset, 'mets')
osp_plotProcess(data_container, num_of_dataset, 'A')
osp_plotFit(data_container, num_of_dataset, 'off');

osp_plotload still works as previously.
osp_plotProcess now seems to have 'metab' instead of 'A' as the 3rd argument.
ops_plotFit - 'off' as the 3rd argument does not work any more. Neither does 'mets' or 'metab'. How should this function be called?

SInce I am using the calls inside another script, switching to the GUI is not an option.

Thanks,
Maarika

**Comment by HJZollner** [comment]
Hi @Maari13, 

Thanks for reaching out!

As you have noticed, we have overhauled the structure of the MRSContainer struct. I've updated the description for the function arguments in #455.

What you will have to do for your scripts is add:
`osp_plotProcess(data_container, num_of_dataset, 'metab','A')`

You can also plot the water data with `'ref','ref'` or different sub-spectra for edited data. In this case you have to change the 'A' entry to 'B', 'diff1', 'diff2', or 'sum'.

`osp_plotFit(data_container, num_of_dataset, 'metab',[1 1 1]);
`

The first index corresponds to the experiment number and currently only 1 is supported. The second index corresponds to the sub-spectrum (always 1 for unedited data see, 1 for edit-off in MEGA, 2 for the difference spectrum, and 3 for the second difference spectrum e.g. HERMES). The third index corresponds to the MM strategy which is only changing if you have supplied metabolite-nulled spectra.

So for unedited data without metabolite-nulled spectra, it will always be [1 1 1].

Hope that helps. Let me know if this works for you.

Helge
