### ISSUE TITLE
[BUG] - Issue with Special Flag - osp_combineCoils 

### ISSUE THREAD

**Issue by marilenad** [schorschinho/osprey#463]
Having issues with the 'isSpecial' flag with HERMES (and PRESS I believe) GE PFiles.

```matlab
Error in osp_combineCoils (line 41)
isSpecial = strcmpi(MRSCont.raw_uncomb{kk}.seq, 'special');
Error in OspreyLoad (line 255)
        [MRSCont] = osp_combineCoils(MRSCont);
Error in osp_onLoad (line 34)
    MRSCont = OspreyLoad(MRSCont);
Error while evaluating UIControl Callback.
```
Worked around by setting the flag `isSpecial = 0` at top of osp_combineCoils.m for now :-)

**Comment by HJZollner** [comment]
Hi @marilenad,

Thanks for reporting this issue. I've just added a fix for this #464.

Hope this works now.

Best,
Helge
