### ISSUE TITLE
[BUG] -io_loadspec_twix Crash When Importing 2+ Datasets - osp_LoadTwix - Mark Britton

### ISSUE THREAD

**Issue by mkwbritton** [schorschinho/osprey#475]
**Describe the bug**
Bug occurs while importing a set of HERMES .dat files in the MATLAB command line (rather than using the Osprey GUI). osp_LoadTwix fails on the second data file with this error message:
`Index in position 2 exceeds array bounds.

Error in mapVBVD>evalMDH (line 782)
mdh.lMeasUID                   = data_uint32(:,2);      %   5 :   8

Error in mapVBVD (line 423)
    [mdh, mask] = evalMDH( mdh_blob, version ); % this is quasi-instant (< 1s) :-)

Error in io_loadspec_twix (line 34)
twix_obj=mapVBVD(filename);

Error in osp_LoadTwix (line 66)
            raw                         = io_loadspec_twix(MRSCont.files{metab_ll,kk});

Error in OspreyLoad (line 181)
                [MRSCont] = osp_LoadTwix(MRSCont);`

Have not been able to reproduce this bug with other data sets. I have tested the data files in different orders, and it only occurs when more than one file is imported simultaneously. Order does not seem to matter.

**To Reproduce**
1. Generate an Osprey jobfile with more than one .dat file and the following options:
```
seqType = 'HERMES';
editTarget = {'GABA', 'GSH', 'EtOH'};

opts.saveLCM = 1;
opts.savejMRUI = 0;
opts.saveVendor = 0;
opts.savePDF = 1;
opts.fit.method = 'Osprey';
opts.fit.includeMetabs = {'default'};
opts.fit.style = 'Separate';
opts.fit.range = [0.2 4.2];
opts.fit.rangeWater = [2.0 7.4];
opts.fit.bLineKnotSpace = 0.4;
opts.fit.fitMM = 1;
opts.fit.coMM3 = '1to1GABA';
opts.fit.FWHMcoMM3 = 14;
opts.SpecReg = 'RobSpecReg';
```
2. Set up jobfile with [MRSCont] = OspreyJob('Jobfile.m')
3. Import data using OspreyLoad. Error message occurs at second .dat file.

**Expected behavior**
Expected behavior is importation of 2+ Twix files with no error.

**Screenshots**
<img width="722" alt="image" src="https://user-images.githubusercontent.com/60443947/181310241-5ef96d84-428c-43c0-841c-84b8070e36a5.png">

**Computer configuration (please complete the following information):**
 - Mac OS
 - Monterey 12.4
 - 2021b
 - Osprey 2.3.0

**Comment by HJZollner** [comment]
Hi @mkwbritton,

Thanks for reaching out! Could you show me how the files cell array is defined in your jobfile and how the struct entry looks like after running OspreyJob?

Best,
Helge

**Comment by mkwbritton** [comment]
Hi Helge,

No problem!

Here is the struct:
```MRSCont = 

  struct with fields:

           flags: [1×1 struct]
            opts: [1×1 struct]
       ospFolder: '/Users/mark.britton/Desktop/Software/osprey-July2022'
           files: {1×2 cell}
        files_mm: {}
       files_ref: {}
         files_w: {}
    files_mm_ref: {}
       files_nii: {1×2 cell}
       files_seg: {}
     files_sense: {}
    outputFolder: '/Users/mark.britton/Desktop/DESA/MRS_Output'
        colormap: [1×1 struct]
       loadedJob: 'DESA_Individual.m'
             ver: [1×1 struct]
      outputFile: 'DESA_Individual.mat'
       nDatasets: 2```

Here is the files cell array:
```files = {'/Users/mark.britton/Desktop/STUDY/SUB-8102/ses-01/mrs/sub-0000_ses-01_run-02_acq-hermes.dat',...
    '/Users/mark.britton/Desktop/STUDY/SUB-0000/ses-01/mrs/sub-0000_ses-01_run-01_acq-hermes.dat'};```

**Comment by HJZollner** [comment]
Just to clarify. You can load a single file, but it crashes as soon as you add a second file to the list?

I'll write you on slack to avoid posting details of the study publicly.

**Comment by HJZollner** [comment]
The issue is related to a corrupted TWIX file and not the loader itself.
