### ISSUE TITLE
[BUG] - Crash When Modeling GABA, GSH, EtOH - osp_editSubSpecAlign  - Mark Britton

### ISSUE THREAD

**Issue by mkwbritton** [schorschinho/osprey#506]
**Describe the bug**
When running HERMES data with GABA, GSH, and EtOH, osp_editSubSpecAlign requires GABA and EtOH to be the second and third targets listed, respectively: the second and third target are read in from OspreyProcess (line 577) when three targets are present. At line 164 of osp_editSubSpecAlign, the targets are checked: if three targets are present, the second and third targets are combined. "GABAGSH" or "GABAEtOH" is expected. "GSHEtOH" or "EtOHGSH" leads to a crash on line 302, so GABA cannot be in the first position. However, putting GSH or EtOH in the first position leads to a crash on line 60 of op_get_Multispectra_SNR. No permutation leads to successful completion of OspreyProcess. I have enclosed screenshots of the crash.

Note that running only GABA and EtOH (without GSH) leads to OspreyProcess completing without errors, but if possible we really want the GSH signal.

**To Reproduce**
1. Set up a fresh HERMES job file.
2. Set "editTarget" to ["EtOH", "GABA", "GSH"] in any order: different crashes result when different orders are specified.
3. Run OspreyJob and OspreyLoad successfully.
4. If GABA is the first target listed, a crash occurs in osp_editSubSpecAlign.
5. If GSH or EtOH is the first target listed, a crash occurs in op_get_Multispectra_SNR.

**Expected behavior**
Expected behavior is completion of OspreyProcess without crashes and successful modeling of GABA, GSH, and EtOH.

**Screenshots**
<img width="909" alt="image" src="https://user-images.githubusercontent.com/60443947/186203340-0e749622-fb82-4946-8873-ea3b1a98c78b.png">
<img width="593" alt="image" src="https://user-images.githubusercontent.com/60443947/186204536-1e39d979-f466-41bc-a7ad-80c1baebd416.png">

**Computer configuration (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.4
 - MATLAB version 2021b
 - Osprey 2.4 (also occurs in Osprey 2.3 and Osprey 2.0)

**Comment by HJZollner** [comment]
Hi @mkwbritton,

thanks for reaching out. I think, three target processing is currently only working for Asp,NAA,NAAG HERMES schemes. Do we already have a test dataset from you to integrate GABA, GSH, EtOH editing or could you provide one for us?

Best,
Helge

**Comment by HJZollner** [comment]
Added full support for GABA-GSH-EtOH HERMES in #587
