### ISSUE TITLE
Batch segmentation

### ISSUE THREAD

**Issue by mdefende** [schorschinho/osprey#537]
I'm not sure whether this is feasible already, but we have a large number of MRS scans across multiple participants and are looking for a quick way to calculate the WM/GM/CSF fraction for a voxel in each scan. We know how to do this through the GUI, but it only does one scan or subject at a time. Is there a way to easily loop through all of our participants and scans and output the segmentation fractions? Thanks

**Comment by HJZollner** [comment]
Hi mdefende, 

thanks for using Osprey and reaching out. I am not sure if I understand this correctly, but I think you are looking for a table including all tissue fractions?  These are stored in the output folder derivatives/SegMaps/TissueFractions_Voxel_1.tsv.

Let me know if this solved your issue
Best,
Helge

**Comment by mdefende** [comment]
Sorry I wasn't very clear before. Basically we have multiple participants with multiple MRS scans each. The current way we know how to perform tissue segmentation for a given MRS voxel is loading the MRS scan and the T1 into the Osprey GUI and going through the Segmentation menu. However, this is time-consuming doing this one participant and MRS scan at a time. Is there a way to essentially loop through all of our participants and their MRS scans to perform voxel segmentation so we don't have to keep going through the GUI menu each time?

**Comment by mdefende** [comment]
Or I guess as a different approach, can we just load all of our participants' MRS and T1w scans into Osprey at the beginning and have segmentation be performed on all of them at once? Is that the way we are supposed to be using Osprey?

**Comment by HJZollner** [comment]
Hi mdefende,

you can look at  …/osprey/exampledata/sdat/UnEdited/jobSDAT.m to see how batch processing works in Osprey. You can run the coregistration and segmentation for all datasets in the jobfile.  I would recommend creating one jobfile per voxel/region. Afterward, you run the analysis for one of the regions. In the second jobfile you add the segmentation outputs (c1…, c2…, c3…) as files_seg cell array (see _…/osprey/exampledata/sdat/UnEdited/jobSDAT.m_ again) to reload the already performed segmentation for the other voxel and calculate the voxel composition.

The final results as a table can be found in the output folder _derivatives/SegMaps/TissueFractions_Voxel_1.tsv_.

Best,
Helge

**Comment by mdefende** [comment]
Thank you for the information, I will share this with the lab.
