### ISSUE TITLE
[FEATURE REQUEST] - Basis set resolution smaller than data resolution - fit_resampleBasis.m - Simon

### ISSUE THREAD

**Issue by fant** [schorschinho/osprey#538]
**Problem description**
For basis sets with a smaller resolution and frequency range than the data, fit_resampleBasis.m creates fringed ends at the resBasisSet.specs 

**Possible solution**
I would suggest updating line 48 to handle cases where the resolution of the basis set is less than the resolution of the data. To do this, the basis set can be extrapolated by zeros to match the resolution of the data: 

`if size(ppmRangeData,1) > size(ppmRangeBasis,2)
   specs_interp(:,ll,rr)      = interp1(ppmRangeBasis(ppmIsInDataRange), basisSet.specs(ppmIsInDataRange,ll,rr), ppmRangeData, 'pchip', 0);
else specs_interp(:,ll,rr)      = interp1(ppmRangeBasis(ppmIsInDataRange), basisSet.specs(ppmIsInDataRange,ll,rr), ppmRangeData, 'pchip', 'extrap');
 end`

**Alternatives**
Alternatively Osprey could only accept basis sets with a resolution exceeding the resolution of the data 

**Additional context**
Plot of the resampled basis set Specta (plot(resBasisSet.ppm, resBasisSet.specs)) before
![resample_before](https://user-images.githubusercontent.com/7209746/203365548-4d005cfd-7dda-470a-bf9a-ab9a093ef5e3.png)
and after adding the lines of code
![resample_after](https://user-images.githubusercontent.com/7209746/203365555-d422ef0f-f791-4f36-9d5a-6ab17b90b987.png)

**Comment by HJZollner** [comment]
Hi @fant,

Thank you for reaching out and directly providing a solution!

I have just pushed your changes onto the develop branch (#539).

I was still wondering how much of an impact this has on the linear-combination modeling later on as we are usually using a smaller frequency range (0 to 4 ppm) during the modeling.

Best,
Helge

**Comment by fant** [comment]
Hi Helge,

Thank you for adding my feature request to develop branch.

On my slaser data the fit considerably improved. Unfortunately, I can't explain how the "frayed ends" of the basis sets outside the frequency range would affect the fit.

Best,

Simon
