### ISSUE TITLE
Glu values mostly zero in PR-STEAM sequence processing and missing group correction in Quantify results

### ISSUE THREAD

**Issue by shaokunzhao** [schorschinho/osprey#576]
Hello,

I'm currently working on processing PR-STEAM sequences and I've noticed that most of the fitted Glu values are 0. I'm wondering if this is an issue with the parameters or if it's related to the basis set generated by the sim_steam.m function from FID-A, which doesn't appear to have been tested. Could this also be affecting the results?

Additionally, I've noticed that the OspreyQuantify results don't include any group correction results. Have I missed any settings or configurations?

I would really appreciate any feedback on these issues. 

Thank you.

**Comment by HJZollner** [comment]
Hi @shaokunzhao,

The accuracy of the basis set has major impact on the quantification, especially for highly j-coupled metabolites. The sim_steam.m function uses ideal excitation and I'd advise you to use  sim_steam_shaped.m instead to generate fully-localized basis spectra. 

Right - this only worked for GABA-edited MEGA-PRESS. I have just added this functionality for unedited data now.

Best,
Helge
