### ISSUE TITLE
[BUG] - Can not import basis set form LCModel correctly.

### ISSUE THREAD

**Issue by shaokunzhao** [schorschinho/osprey#592]
**Describe the bug**
Can not import basis set form LCModel correctly.

**To Reproduce**
1 Run the function `[BASIS]` = io_LCMBasis(basis_folder, 0, 'unedited', 'none');

**Screenshots**
![image](https://user-images.githubusercontent.com/27758467/223616817-425df8da-2ff6-4621-9075-fa6e1211e39c.png)

**Computer configuration (please complete the following information):**
 - OS: Windows 
 - Version: 11
 - MATLAB version 2022b

Hello,

I am using the `io_LCMBasis` function in Osprey to read basis sets from LCMdel, but I'm encountering some issues that do not occur when reading the built-in .basis files in Osprey. Specifically, when I try to import press_te30_3t_v3.basis, MATLAB does not respond and I have to force quit.

I suspect that the bug I initially reported may be related to not specifying the .basis file name. If this is the case, can you please modify the relevant content in 7.1 io_LCMBasis?

Thank you for your help.

**Comment by HJZollner** [comment]
Hi @shaokunzhao,

I have just added an update version of io_LCMBasis.m to the develop branch. This one should be able to read the _v3.basis files from LCModel.

You should be able to run it as follows:
[BASIS] = io_LCMBasis('.../3t/all/press_te30_3t_all_v3.basis',1,'unedited','none',0)

The previous version failed for several reasons:
- .basis files are not standardized and sometimes contain unexpected whitespace etc.
- the _v3 basis files from the LCModel website are encrypted and need an additional step to work

Another comment is that I would not use this basis set as it is a measured one with unknown settings, pulse timings, vendor etc.  I highly recommend using the basis sets already included in Osprey which are simulated using matrix density formalism. You can also use the tools on MRSCliud (https://onlinelibrary.wiley.com/doi/10.1002/mrm.29370) to generate a new basis set for Osprey (or LCModel) if your specific echo time is not available by default.

Best,
Helge
