### ISSUE TITLE
[FEATURE REQUEST] - Fit Error - How can i obtain the "Fit Error" value for subsequent QC?

### ISSUE THREAD

**Issue by shaokunzhao** [schorschinho/osprey#595]
Hi,

I am using Osprey for fitting, and I have noticed that there is no mention of fit error during the fitting process. I am wondering if I have missed any information or if it is possible to include this information in the generated report after fitting. This would be helpful for quality control purposes. 

Thank you.

**Comment by HJZollner** [comment]
Hi @shaokunzhao,

The fit error in Osprey is currently calculated as a spectrum-wide fit error defined as the amplitude of the residual normalized by the noise. It is stored in the MRS container MRSCont.QM.relAmpl for each sub spectrum that was analyzed. It is also stored in the QM_processed_spectra.tsv file.

We are currently not calculating metabolite specific CRLBs. However, we are working on a new fit model which will inlcude those.

Best,
Helge
