### ISSUE TITLE
[BUG] - Error in osp_fit_Quality when using LCModel

### ISSUE THREAD

**Issue by peter-mri** [schorschinho/osprey#655]
I was getting an error trying to use LCModel fitting on unedited spectra with custom basis set, loading Philips SDAT data, with both long and short echo water files.

MRSCont=OspreyFit(MRSCont);
Timestamp August 24, 2023 19:01:09 Osprey 2.5.0  OspreyFit
Fitting metabolite spectra from dataset   1 out of   1 total datasets...

... done.
 Elapsed time 5.624957 seconds

... done.
 Elapsed time 5.624957 seconds
Error using orderfields
Text in second input must match fieldnames of the struct.

Error in osp_fit_Quality (line 60)
S = orderfields(MRSCont.fit.results,OrderNamesFit);

Error in OspreyFit (line 147)
    [MRSCont] = osp_fit_Quality(MRSCont);

I solved it by editing osp_fit_Quality.m adding a condition for LCModel fit
line 55
if MRSCont.flags.hasWater
    OrderNames = horzcat(OrderNames, 'w');
    if ~strcmp(MRSCont.opts.fit.method,'LCModel')  % -ps-
        OrderNamesFit = horzcat(OrderNamesFit, 'w');
    end    
end

**Comment by HJZollner** [comment]
Hi @peter-mri,

thank you fro reporting and solving the issue. I have just updated the current develop branch accordingly (#665).

Best,
Helge
