### ISSUE TITLE
[BUG] - Exporting figures from the Overview tap

### ISSUE THREAD

**Issue by shui5** [schorschinho/osprey#662]
**Describe the bug**
wanted to report a known issue for exporting figures from the Overview tap. It gives me the Model metab A figure even I have selected to export the diff. figure. To resolve this issue, put a break point at the beginning of the osp_plotMeanSpec.m and then manually change the input argument which_spec to Model metab diff1.

**Comment by HJZollner** [comment]
Thanks for reporting @shui5.

I have implemented a bug fix that allows the correct export of all spectra from within the GUI (#666 ).
