### ISSUE TITLE
[Question] Compiled CMD availabliity

### ISSUE THREAD

**Issue by bloyl** [schorschinho/osprey#704]
Hi,

I'm have difficulty building a standalone osprey command line utility using `CompileOspreyStandalone`.

The most success I have had is buidling one that mostly works but can't save pdfs (I think because it lacks the GUI add-ons) or run spm segmentation.

Are there any available for ubuntu, either as a standalone zip or as a docker container?

Thanks
Luke

**Comment by HJZollner** [comment]
Hi Luke,

Thanks for reaching out. Could you try adding the GUILayoutDir and WidgetsDir to the list of additional files for the CmdCompiler as well? Should be those two lines:

```
fullfile(WidgetsDir),...
fullfile(GUILayoutDir),...
```

Or have you already done this?

Not sure about the SPM issue can you post the logfile output?

Have you tried the Ubuntu GUI version from the release page? Just to be sure that it is working. I can try and compile a working CMD version for Ubuntu in the meantime.

Cheers,
Helge

**Comment by bloyl** [comment]
I think I can fix the pdf issue. I hadn't realized those weren't included in the build script. But I'm confident I can get that to work since it works in my GUI version.

I get the same SPM errror when using my compiled GUI version. below is the error 

> Timestamp March 27, 2024 15:33:50 Osprey 2.5.0  OspreyCoreg
> Coregistering voxel from dataset   1 out of   1 total datasets...
> ... done.
>  Elapsed time 5.273914 seconds
> Timestamp March 27, 2024 15:34:12 Osprey 2.5.0  OspreySeg
> Segmenting structural image from dataset   1 out of   1 total datasets...
> Item matlabbatch: No repeat named
> spm
> Incorrect number or types of inputs or outputs for function 'list'.
> Error in cfg_repeat/list (line 112)
> Error in cfg_util>local_getcjid2subs (line 1365)
> Error in cfg_util>local_initjob (line 1555)
> Error in cfg_util (line 815)
> Error in spm_jobman (line 246)
> Error in OspreySeg>createSegJob (line 740)
> Error in OspreySeg (line 191)
> Error in osp_onSeg (line 47)
> Error while evaluating UIControl Callback.
> 

Its worth noting that when I use the GUI version available from the release page `segment` seems to work.

**Comment by bloyl** [comment]
It probably worth posting how I'm calling the build script.

```
clear all
addpath('spm12')
addpath(genpath('osprey'))

CompileOspreyStandalone('/mnt/isilon/meg_lab/bloyl/Programs/osprey/cli2_2', ...
    '/mnt/isilon/meg_lab/bloyl/Programs/osprey/spm12', ...
    0, 1, 1, 0, ...
    '/home/bloyl/MATLAB Add-Ons/Toolboxes/Widgets Toolbox - Compatibility Support(3)', ...
    '/home/bloyl/MATLAB Add-Ons/Toolboxes/GUI Layout Toolbox')
```

does that seem correct? Specifically the addpath s?

Thanks for your help on this.

**Comment by HJZollner** [comment]
Sorry for the delayed answer.

The function call looks correct to me.

Did you figure out the problem with SPM?
