### ISSUE TITLE
[Question] Issue Processing Siemens/Megapress Data in Osprey

### ISSUE THREAD

**Issue by CarlosLeandro09** [schorschinho/osprey#720]
Hello everyone,

I'm encountering an issue while processing my Siemens/megapress data in Osprey and would like to ask for your help in resolving it. Whenever I try to execute the process, I receive the following errors (see the attached image).

**- Using nifti:**

![Captura_18_04_24](https://github.com/schorschinho/osprey/assets/66041961/83582d04-ed5c-4b64-903d-4fbd3713748e)

**- Using RDA:**

![error_osprey](https://github.com/schorschinho/osprey/assets/66041961/9477e1fa-3c68-4b9d-b1ec-c715ad7c8b97)

I've already tried some solutions, such as converting to NIFT and processing RDA instead of TWIX data, but so far, I haven't been able to solve the problem.

**Any help would be greatly appreciated.
Thank you in advance!**

**Comment by HJZollner** [comment]
Hi @CarlosLeandro09,

I have opened a discussion on MRSHub.org. I'll close this here.

Helge
