### ISSUE TITLE
[BUG] - osp_saveNII fails if water signal does not originate from a separate data file - osp_saveNII

### ISSUE THREAD

**Issue by alexcraven** [schorschinho/osprey#728]
**Describe the bug**

Some GE P-files incorporate metabolite, reference and water data in the same file.

In these cases, [osp_LoadP](https://github.com/schorschinho/osprey/blob/develop/load/osp_LoadP.m#L57) sets the hasWater flag, but `MRSCont.files_w` remains empty.

This causes [osp_saveNII](https://github.com/schorschinho/osprey/blob/develop/process/osp_saveNII.m#L132) to fail:

```Index exceeds the number of array elements (0).

Error in osp_saveNII (line 132)
        [path_w,filename_w,ext_w]   = fileparts(MRSCont.files_w{kk});

Error in OspreyProcess (line 853)
    [MRSCont] = osp_saveNII(MRSCont);
```

**Suggested Fix**

osp_saveNII could replicate behavior from [the hasRef condition](https://github.com/schorschinho/osprey/blob/develop/process/osp_saveNII.m#L106) immediately above for GE data (or more generally, any case where files_w is empty)?

**Comment by HJZollner** [comment]
Thanks Alex. I think, your solution should work fine.

Added in #739
