### ISSUE TITLE
[BUG] SPM error message when starting GUI

### ISSUE THREAD

**Issue by schorschinho** [schorschinho/osprey#73]
If the SPM and Osprey folders are not in the same (MATLAB) folder, an error is being thrown when the GUI is initialized (when OspreyGUI is called after OspreyStartUp has been run and a job file has been selected).

**Comment by hezoe100** [comment]
GUIupdate #84 

SPM folder is located during the first startup of the GUI and afterwards stored in a mat file within the GUI folder
