### ISSUE TITLE
[FEATURE REQUEST] Make Fit module independent from Curve Fitting Toolbox

### ISSUE THREAD

**Issue by schorschinho** [schorschinho/osprey#75]
The fit module currently relies on the 'spmak' function from the Curve Fitting Toolbox. Construct the spline basis functions individually, without the use of spmak.

**Comment by FredericBr** [comment]
Hi @schorschinho 
Any improvement?
I am currently try your (great) software, but I obtain this mistake:
```
To use 'spmak', the following product must be licensed, installed, and enabled:
  Curve Fitting Toolbox
```
Do I have to buy the Curve Fitting Toolbox?
Thanks!

**Comment by schorschinho** [comment]
Hi Frederic,

Thanks for reaching out! I think I know how to do it, but I haven't made much progress on it yet. Let me spend some time on it next week, and I'll get back to you here. Do you have any other toolboxes available or installed?

Best wishes,
Georg

**Comment by FredericBr** [comment]
Thanks for your quick reply Georg.
My purchase of the licence for Curve Fitting toolbox is in progress, thus no hurry.
I am confuse but I'm not sure what your question is about. Concerning your software, I have several toolboxes: Image processing, Optimization, Signal Processing and Statistics and Machine Learning.
For MRS toolboxes, I also use jMRUI, LCModel and Tarquin.

Best,
Frederic

**Comment by FredericBr** [comment]
Hi @schorschinho,
Hope your are well.
I am still used an previous version of Osprey (with Curve Fitting Toolbox). In the new version, do you still need of this toolbox?
Best,
Frederic
