### ISSUE TITLE
typo in the documentation on github pages

### ISSUE THREAD

**Issue by juliam98** [schorschinho/osprey#756]
There is a typo in this line of Osprey documentation on github pages:

https://github.com/schorschinho/osprey/blob/87b32c45c59cefff78f4162c3ab2c49a4c1097fb/docs_source/05-tutorial_cmd.Rmd#L17

Change to:
```
MRSCont = OspreyLoad(MRSCont); 
 ```

I know it's minor, but I copy the commands from this page one by one and keep getting an error cause I forget there's a typo there. Thanks!

**Comment by HJZollner** [comment]
Hi @juliam98,

Thank you for pointing this out. 

Fixed this in #761
