### ISSUE TITLE
[BUG] - Issues with averaged IMA data - io_loadspec_dicom - Alex Craven

### ISSUE THREAD

**Issue by alexcraven** [schorschinho/osprey#757]
**Describe the bug**

If a given folder contains multiple pre-averaged IMA (DCM) files, io_loadspec_dicom incorrectly insists on interpreting these as unaveraged data and combining all files in the folder, even if an individual file was explicitly requested. This breaks for datasets like [this one](https://openneuro.org/datasets/ds003823/versions/1.3.3) where preprocessed reference, ECC and non-ECC spectra are grouped into a single folder per subject, per voxel -- a reasonably intuitive way of organising this data.

**Comment by schorschinho** [comment]
Thank you Alex, as always, for your thoughtful suggestions. It is difficult to anticipate how MRS-DICOM data are organized, and in the early days of writing these DICOM readers we have certainly not seen enough variety to capture all the scenarios. Most data we saw back then was MEGA data with 1 DICOM file per transient.

I like your proposed fix (as it would appear to preserve the existing functionality seamlessly); the alternative might be to add an optional argument to `io_loadspec_dicom` that forces the function to load *only* the specified file, not all files of the folder it is in. But using the series number tag feels more elegant to me, so I would welcome your suggested fix.

**Comment by alexcraven** [comment]
Great, then it is fixed as suggested. Thanks Karlijn for flagging this issue!

**Comment by HJZollner** [comment]
Changes are added in #758
