### ISSUE TITLE
[BUG] - Error starting "Process Data" when trying to calculate GABA edited MEGA PRESS on Siemens

### ISSUE THREAD

**Issue by tkhauser** [schorschinho/osprey#784]
**Describe the bug**
Loading the TWIX files (GABA edited sequence and non water suppressed reference scan) works perfectly and they are displayed correctly. When I go to "Process Data" I get the following error:

Arrays have incompatible sizes for this operation.
Error in op_eccKlose (line 47)
    out.fids=out.fids.*exp(1i*-inph);
Error in OspreyProcess (line 376)
                    [raw,raw_ref]                   = op_eccKlose(raw, raw_ref);        % Klose eddy current correction
Error in osp_onProc (line 37)
    MRSCont = OspreyProcess(MRSCont);
Related documentation 
Error while evaluating UIControl Callback.

**To Reproduce**
1. Create Job file (enter GABA.dat and GABA_no_water_suppression.dat)
2. Load Data
3. Process Data

**Expected behavior**
Alignment and averaging of the spectra should be done and displayed

**Screenshots**

**Computer configuration (please complete the following information):**
 - OS: Mac OS Seuoia15
 - Version Osprey 2.8.0 (downloaded today)
 - MATLAB version 2024A

**Additional context**
Thank you for supplying this great piece of software!

**Comment by HJZollner** [comment]
Hi @tkhauser,

Thanks for reaching out. Could you take a look at the number of points of the metabolite and the water scan? I am wondering if they have different number of datapoints.

It should be possible to fix this in the code, but I just wanted to be sure that this is the problem first.

Thank you,
Helge

**Comment by tkhauser** [comment]
After loading in Osprey, the metabolite scan shows Sz=2080 whereas the water scan shows Sz=2066.
2080 datapoints is also what Gannet gives me although it does not mention the water reference scan.
I am not sure I can set this in the scanning parameters.

**Comment by HJZollner** [comment]
Hi @tkhauser,
Sorry for the delayed response. Would you be able to share the data. It seems like an issue with the loader that needs fixing.
Best,
Helge

**Comment by tkhauser** [comment]
Hi Helge,
Thanx for looking into this!
I just shared the files via cloud link to your email adress as they exceed the upload limit.
best
Till

**Comment by HJZollner** [comment]
Issued resolved offline. As noted, the metabolite and water scans have different numbers of data points. Both scans are acquired with different sequences (MEGA-PRES WIP and PRESS product) with different points before the actual FID. Therefore, ECC is not possible with this combination of files.
