### ISSUE TITLE
[BUG] - OspreyLoad cannot read GE data with extension .7.anon - osp_detDataType.m - Steve Hui

### ISSUE THREAD

**Issue by shui5** [schorschinho/osprey#788]
**Describe the bug**
OspreyLoad cannot read GE data with extension .7.anon

**To Reproduce**
Run a GE data with .7.anon extension

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-02 160144](https://github.com/user-attachments/assets/f8433ff3-db0a-4640-ac30-749c61a1e727)

**Computer configuration (please complete the following information):**
 - OS: Win11
 - Version 23H2
 - MATLAB version 2023b

**Additional context**
Solved by changing line 152 in osp_detDataType.m to the following.
        if strcmpi(ext,'.7') || strcmpi(ext,'.anon')

**Comment by HJZollner** [comment]
Thanks for reporting this @shui5. Solved in  #796
