### ISSUE TITLE
[BUG] - Error in OspreyLoad for GE 3T MEGA-PRESS - Steve Hui

### ISSUE THREAD

**Issue by shui5** [schorschinho/osprey#791]
**Describe the bug**
Load error for GE 3T MEGA-PRESS data

**To Reproduce**
Run MRSCont = OspreyLoad(MRSCont);

**Expected behavior**
Load data.

**Screenshots**
![Screenshot 2024-10-18 104145](https://github.com/user-attachments/assets/a517fb01-7fcd-4b4f-b0db-e2d608ab1364)

**Computer configuration (please complete the following information):**
 - OS: Win11
 - Version 23H2
 - MATLAB version 2023b

**Additional context**

**Comment by HJZollner** [comment]
Thank you for reporting this @shui5. Just added a fix to the develop branch #795 .
