### ISSUE TITLE
[BUG] - Recent osp_combineCoils breaks compatibility with GE P-file loader (and presumably others)

### ISSUE THREAD

**Issue by alexcraven** [schorschinho/osprey#792]
**Describe the bug**

`OspreyLoad` => `osp_combineCoils` now fails with GE P-files (and presumably others)

<https://github.com/schorschinho/osprey/blame/101ed7a56ee26eccea5ee21852fd62e29d8e8450/process/osp_combineCoils.m#L47C13-L47C84>

`osp_combineCoils` line 47, commit 39dd9d6 replaced:

isSpecial = strcmpi(MRSCont.raw_uncomb{metab_ll,kk}.seq, 'special');

With:

isSpecial = strcmpi(MRSCont.raw_uncomb{metab_ll,kk}.seq(1), 'special');

For many cases, "`.seq`" is a single string, so this indexing is not meaningful. Luckily (coincidentally) if `.seq` is a non-empty string it doesn't actually fail... but for cases where "`.seq`" remains empty, this crashes.

I'm not sure what format the special data is, but perhaps a better fix would be to collapse ".seq" into a single string within the reader for that format?

**Comment by alexcraven** [comment]
(this is the same underlying issue as in #791)

**Comment by HJZollner** [comment]
Thanks for reporting this Solved in #795
