### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darksim33** [schorschinho/osprey#95]
SplineArray dimension calculation Error

HERCULES fit with _LCmodel_ and _seperate_ style

For default fitting range the dimension of the spline array and the reduced data/basis set range can disagree.
Possible Error in _fit_makeSplineBasis_ line 99
splineInnerBasisFunctionMatrix(:,rr,:) = splineBasisFunctionMatrix(**knotLocations(3):1:knotLocations(end-2)**,rr,:);
Maybe due to a wrong knot location resulting from _dkntmn_.

Changing Fit Range somehow bypasses this Problem.

**Comment by schorschinho** [comment]
Thank you darksim33. I've seen this error before - changing the knot spacing by 0.01 ppm or so also resolves these errors. I think it originates from the rounding when we determine the number of knots - I'll have to look into it in detail.

**Comment by hezoe100** [comment]
Thanks again for your bug report darksim33.

We have added another argument to the op_freqrange() function which controls whether the number of points of the parsed data/basis set is consistent with a user defined number of points. It will automatically account for slight differences by cutting the upfield ppm range value.

This is used to compare the dimensions of the data/basis set to the splineArray.
dataToFit   = op_freqrange(dataToFit, fitRangePPM(1),fitRangePPM(end),length(splineArray(:,1,1)));
